/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockIdentityVerificationHub,
  MockIdentityVerificationHubInterface,
} from "../../contracts/MockIdentityVerificationHub";

const _abi = [
  {
    inputs: [],
    name: "mockFunction",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600f57600080fd5b50607780601d6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80633e6fec0414602d575b600080fd5b604080516001815290519081900360200190f3fea26469706673582212205a58093e927da303ba13a0643337170a8c05015eb801d3ff6cac22073d32474764736f6c634300081c0033";

type MockIdentityVerificationHubConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockIdentityVerificationHubConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockIdentityVerificationHub__factory extends ContractFactory {
  constructor(...args: MockIdentityVerificationHubConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockIdentityVerificationHub & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockIdentityVerificationHub__factory {
    return super.connect(runner) as MockIdentityVerificationHub__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockIdentityVerificationHubInterface {
    return new Interface(_abi) as MockIdentityVerificationHubInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockIdentityVerificationHub {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockIdentityVerificationHub;
  }
}
