/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as reliefPoolsSol from "./ReliefPools.sol";
export type { reliefPoolsSol };
export type { IdentityVerifier } from "./IdentityVerifier";
export type { Lock } from "./Lock";
export type { TypedMemView } from "./TypedMemView";
