/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDscCircuitVerifier } from "./IDscCircuitVerifier";
export type { IIdentityVerificationHubV2 } from "./IIdentityVerificationHubV2";
export type { IRegisterCircuitVerifier } from "./IRegisterCircuitVerifier";
export type { ISelfVerificationRoot } from "./ISelfVerificationRoot";
