/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMessageHandlerV2 } from "./IMessageHandlerV2";
export type { ReliefPools } from "./ReliefPools";
