/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace ReliefPools {
  export type BeneficiaryStruct = {
    nullifier: BigNumberish;
    userIdentifier: BigNumberish;
    walletAddress: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
  };

  export type BeneficiaryStructOutput = [
    nullifier: bigint,
    userIdentifier: bigint,
    walletAddress: string,
    amount: bigint,
    timestamp: bigint
  ] & {
    nullifier: bigint;
    userIdentifier: bigint;
    walletAddress: string;
    amount: bigint;
    timestamp: bigint;
  };

  export type DonorStruct = {
    id: BigNumberish;
    walletAddress: AddressLike;
    amount: BigNumberish;
    timestamp: BigNumberish;
    isCrossChain: boolean;
    sourceDomain: BigNumberish;
    location: string;
  };

  export type DonorStructOutput = [
    id: bigint,
    walletAddress: string,
    amount: bigint,
    timestamp: bigint,
    isCrossChain: boolean,
    sourceDomain: bigint,
    location: string
  ] & {
    id: bigint;
    walletAddress: string;
    amount: bigint;
    timestamp: bigint;
    isCrossChain: boolean;
    sourceDomain: bigint;
    location: string;
  };

  export type ReliefPoolStruct = {
    id: BigNumberish;
    disasterType: BigNumberish;
    classification: BigNumberish;
    nationalityRequired: string;
    allocatedFundsPerPerson: BigNumberish;
    totalBeneficiaries: BigNumberish;
    totalDonors: BigNumberish;
    totalAmountClaimed: BigNumberish;
    totalAmountDonated: BigNumberish;
    isActive: boolean;
  };

  export type ReliefPoolStructOutput = [
    id: bigint,
    disasterType: bigint,
    classification: bigint,
    nationalityRequired: string,
    allocatedFundsPerPerson: bigint,
    totalBeneficiaries: bigint,
    totalDonors: bigint,
    totalAmountClaimed: bigint,
    totalAmountDonated: bigint,
    isActive: boolean
  ] & {
    id: bigint;
    disasterType: bigint;
    classification: bigint;
    nationalityRequired: string;
    allocatedFundsPerPerson: bigint;
    totalBeneficiaries: bigint;
    totalDonors: bigint;
    totalAmountClaimed: bigint;
    totalAmountDonated: bigint;
    isActive: boolean;
  };
}

export interface ReliefPoolsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DOMAIN_SEPARATOR"
      | "VERIFICATION_MESSAGE_TYPEHASH"
      | "_processCrossChainDonation"
      | "adminAddress"
      | "cctpMessageTransmitter"
      | "checkPersonClaimedFromPool"
      | "claimRelief"
      | "claimReliefToSelf"
      | "createReliefPool"
      | "donate"
      | "emergencyWithdraw"
      | "getBeneficiary"
      | "getContractBalance"
      | "getDonor"
      | "getPersonClaimedPools"
      | "getReliefPool"
      | "getTotalPools"
      | "handleReceiveFinalizedMessage"
      | "handleReceiveUnfinalizedMessage"
      | "hasPersonClaimedFromPool"
      | "owner"
      | "personClaimedPools"
      | "poolBeneficiaries"
      | "poolCounter"
      | "poolDonors"
      | "reliefPools"
      | "renounceOwnership"
      | "setCCTPMessageTransmitter"
      | "togglePoolStatus"
      | "transferOwnership"
      | "usdcToken"
      | "verifyAdminSignature"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DonationMade"
      | "FundsClaimed"
      | "OwnershipTransferred"
      | "PoolStatusChanged"
      | "ReliefPoolCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DOMAIN_SEPARATOR",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFICATION_MESSAGE_TYPEHASH",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_processCrossChainDonation",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cctpMessageTransmitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkPersonClaimedFromPool",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimRelief",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      AddressLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReliefToSelf",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createReliefPool",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "donate",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBeneficiary",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDonor",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPersonClaimedPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getReliefPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handleReceiveFinalizedMessage",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "handleReceiveUnfinalizedMessage",
    values: [BigNumberish, BytesLike, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasPersonClaimedFromPool",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "personClaimedPools",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "poolBeneficiaries",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "poolCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "poolDonors",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reliefPools",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCCTPMessageTransmitter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "togglePoolStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdcToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifyAdminSignature",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      string,
      BigNumberish,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "DOMAIN_SEPARATOR",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFICATION_MESSAGE_TYPEHASH",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_processCrossChainDonation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cctpMessageTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkPersonClaimedFromPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimRelief",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReliefToSelf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createReliefPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "donate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDonor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPersonClaimedPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReliefPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleReceiveFinalizedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleReceiveUnfinalizedMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasPersonClaimedFromPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "personClaimedPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolBeneficiaries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "poolCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "poolDonors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reliefPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCCTPMessageTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "togglePoolStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdcToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifyAdminSignature",
    data: BytesLike
  ): Result;
}

export namespace DonationMadeEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    donor: AddressLike,
    sourceDomain: BigNumberish,
    amount: BigNumberish,
    timestamp: BigNumberish,
    location: string
  ];
  export type OutputTuple = [
    poolId: bigint,
    donor: string,
    sourceDomain: bigint,
    amount: bigint,
    timestamp: bigint,
    location: string
  ];
  export interface OutputObject {
    poolId: bigint;
    donor: string;
    sourceDomain: bigint;
    amount: bigint;
    timestamp: bigint;
    location: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FundsClaimedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    claimer: AddressLike,
    recipient: AddressLike,
    nullifier: BigNumberish,
    userIdentifier: BigNumberish,
    nationality: string,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    claimer: string,
    recipient: string,
    nullifier: bigint,
    userIdentifier: bigint,
    nationality: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    claimer: string;
    recipient: string;
    nullifier: bigint;
    userIdentifier: bigint;
    nationality: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolStatusChangedEvent {
  export type InputTuple = [poolId: BigNumberish, isActive: boolean];
  export type OutputTuple = [poolId: bigint, isActive: boolean];
  export interface OutputObject {
    poolId: bigint;
    isActive: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReliefPoolCreatedEvent {
  export type InputTuple = [
    poolId: BigNumberish,
    disasterType: BigNumberish,
    classification: BigNumberish,
    nationalityRequired: string,
    allocatedFundsPerPerson: BigNumberish
  ];
  export type OutputTuple = [
    poolId: bigint,
    disasterType: bigint,
    classification: bigint,
    nationalityRequired: string,
    allocatedFundsPerPerson: bigint
  ];
  export interface OutputObject {
    poolId: bigint;
    disasterType: bigint;
    classification: bigint;
    nationalityRequired: string;
    allocatedFundsPerPerson: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReliefPools extends BaseContract {
  connect(runner?: ContractRunner | null): ReliefPools;
  waitForDeployment(): Promise<this>;

  interface: ReliefPoolsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DOMAIN_SEPARATOR: TypedContractMethod<[], [string], "view">;

  VERIFICATION_MESSAGE_TYPEHASH: TypedContractMethod<[], [string], "view">;

  _processCrossChainDonation: TypedContractMethod<
    [sourceDomain: BigNumberish, sender: BytesLike, messageBody: BytesLike],
    [void],
    "nonpayable"
  >;

  adminAddress: TypedContractMethod<[], [string], "view">;

  cctpMessageTransmitter: TypedContractMethod<[], [string], "view">;

  checkPersonClaimedFromPool: TypedContractMethod<
    [poolId: BigNumberish, userIdentifier: BigNumberish],
    [boolean],
    "view"
  >;

  claimRelief: TypedContractMethod<
    [
      poolId: BigNumberish,
      nullifier: BigNumberish,
      userIdentifier: BigNumberish,
      nationality: string,
      timestamp: BigNumberish,
      recipient: AddressLike,
      adminSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  claimReliefToSelf: TypedContractMethod<
    [
      poolId: BigNumberish,
      nullifier: BigNumberish,
      userIdentifier: BigNumberish,
      nationality: string,
      timestamp: BigNumberish,
      adminSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createReliefPool: TypedContractMethod<
    [
      disasterType: BigNumberish,
      classification: BigNumberish,
      nationalityRequired: string,
      allocatedFundsPerPerson: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  donate: TypedContractMethod<
    [poolId: BigNumberish, amount: BigNumberish, location: string],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getBeneficiary: TypedContractMethod<
    [poolId: BigNumberish, beneficiary: AddressLike],
    [ReliefPools.BeneficiaryStructOutput],
    "view"
  >;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getDonor: TypedContractMethod<
    [poolId: BigNumberish, donor: AddressLike],
    [ReliefPools.DonorStructOutput],
    "view"
  >;

  getPersonClaimedPools: TypedContractMethod<
    [userIdentifier: BigNumberish],
    [bigint[]],
    "view"
  >;

  getReliefPool: TypedContractMethod<
    [poolId: BigNumberish],
    [ReliefPools.ReliefPoolStructOutput],
    "view"
  >;

  getTotalPools: TypedContractMethod<[], [bigint], "view">;

  handleReceiveFinalizedMessage: TypedContractMethod<
    [
      sourceDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  handleReceiveUnfinalizedMessage: TypedContractMethod<
    [
      sourceDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;

  hasPersonClaimedFromPool: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  personClaimedPools: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  poolBeneficiaries: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, string, bigint, bigint] & {
        nullifier: bigint;
        userIdentifier: bigint;
        walletAddress: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  poolCounter: TypedContractMethod<[], [bigint], "view">;

  poolDonors: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, string, bigint, bigint, boolean, bigint, string] & {
        id: bigint;
        walletAddress: string;
        amount: bigint;
        timestamp: bigint;
        isCrossChain: boolean;
        sourceDomain: bigint;
        location: string;
      }
    ],
    "view"
  >;

  reliefPools: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        disasterType: bigint;
        classification: bigint;
        nationalityRequired: string;
        allocatedFundsPerPerson: bigint;
        totalBeneficiaries: bigint;
        totalDonors: bigint;
        totalAmountClaimed: bigint;
        totalAmountDonated: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setCCTPMessageTransmitter: TypedContractMethod<
    [_cctpMessageTransmitter: AddressLike],
    [void],
    "nonpayable"
  >;

  togglePoolStatus: TypedContractMethod<
    [poolId: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdcToken: TypedContractMethod<[], [string], "view">;

  verifyAdminSignature: TypedContractMethod<
    [
      userAddress: AddressLike,
      nullifier: BigNumberish,
      userIdentifier: BigNumberish,
      nationality: string,
      timestamp: BigNumberish,
      adminSignature: BytesLike
    ],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DOMAIN_SEPARATOR"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFICATION_MESSAGE_TYPEHASH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "_processCrossChainDonation"
  ): TypedContractMethod<
    [sourceDomain: BigNumberish, sender: BytesLike, messageBody: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adminAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cctpMessageTransmitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkPersonClaimedFromPool"
  ): TypedContractMethod<
    [poolId: BigNumberish, userIdentifier: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimRelief"
  ): TypedContractMethod<
    [
      poolId: BigNumberish,
      nullifier: BigNumberish,
      userIdentifier: BigNumberish,
      nationality: string,
      timestamp: BigNumberish,
      recipient: AddressLike,
      adminSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimReliefToSelf"
  ): TypedContractMethod<
    [
      poolId: BigNumberish,
      nullifier: BigNumberish,
      userIdentifier: BigNumberish,
      nationality: string,
      timestamp: BigNumberish,
      adminSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createReliefPool"
  ): TypedContractMethod<
    [
      disasterType: BigNumberish,
      classification: BigNumberish,
      nationalityRequired: string,
      allocatedFundsPerPerson: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "donate"
  ): TypedContractMethod<
    [poolId: BigNumberish, amount: BigNumberish, location: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getBeneficiary"
  ): TypedContractMethod<
    [poolId: BigNumberish, beneficiary: AddressLike],
    [ReliefPools.BeneficiaryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDonor"
  ): TypedContractMethod<
    [poolId: BigNumberish, donor: AddressLike],
    [ReliefPools.DonorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPersonClaimedPools"
  ): TypedContractMethod<[userIdentifier: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getReliefPool"
  ): TypedContractMethod<
    [poolId: BigNumberish],
    [ReliefPools.ReliefPoolStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalPools"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "handleReceiveFinalizedMessage"
  ): TypedContractMethod<
    [
      sourceDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "handleReceiveUnfinalizedMessage"
  ): TypedContractMethod<
    [
      sourceDomain: BigNumberish,
      sender: BytesLike,
      finalityThresholdExecuted: BigNumberish,
      messageBody: BytesLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasPersonClaimedFromPool"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "personClaimedPools"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolBeneficiaries"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, bigint, string, bigint, bigint] & {
        nullifier: bigint;
        userIdentifier: bigint;
        walletAddress: string;
        amount: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "poolCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "poolDonors"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [
      [bigint, string, bigint, bigint, boolean, bigint, string] & {
        id: bigint;
        walletAddress: string;
        amount: bigint;
        timestamp: bigint;
        isCrossChain: boolean;
        sourceDomain: bigint;
        location: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "reliefPools"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        disasterType: bigint;
        classification: bigint;
        nationalityRequired: string;
        allocatedFundsPerPerson: bigint;
        totalBeneficiaries: bigint;
        totalDonors: bigint;
        totalAmountClaimed: bigint;
        totalAmountDonated: bigint;
        isActive: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCCTPMessageTransmitter"
  ): TypedContractMethod<
    [_cctpMessageTransmitter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "togglePoolStatus"
  ): TypedContractMethod<[poolId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdcToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifyAdminSignature"
  ): TypedContractMethod<
    [
      userAddress: AddressLike,
      nullifier: BigNumberish,
      userIdentifier: BigNumberish,
      nationality: string,
      timestamp: BigNumberish,
      adminSignature: BytesLike
    ],
    [boolean],
    "view"
  >;

  getEvent(
    key: "DonationMade"
  ): TypedContractEvent<
    DonationMadeEvent.InputTuple,
    DonationMadeEvent.OutputTuple,
    DonationMadeEvent.OutputObject
  >;
  getEvent(
    key: "FundsClaimed"
  ): TypedContractEvent<
    FundsClaimedEvent.InputTuple,
    FundsClaimedEvent.OutputTuple,
    FundsClaimedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PoolStatusChanged"
  ): TypedContractEvent<
    PoolStatusChangedEvent.InputTuple,
    PoolStatusChangedEvent.OutputTuple,
    PoolStatusChangedEvent.OutputObject
  >;
  getEvent(
    key: "ReliefPoolCreated"
  ): TypedContractEvent<
    ReliefPoolCreatedEvent.InputTuple,
    ReliefPoolCreatedEvent.OutputTuple,
    ReliefPoolCreatedEvent.OutputObject
  >;

  filters: {
    "DonationMade(uint256,address,uint32,uint256,uint256,string)": TypedContractEvent<
      DonationMadeEvent.InputTuple,
      DonationMadeEvent.OutputTuple,
      DonationMadeEvent.OutputObject
    >;
    DonationMade: TypedContractEvent<
      DonationMadeEvent.InputTuple,
      DonationMadeEvent.OutputTuple,
      DonationMadeEvent.OutputObject
    >;

    "FundsClaimed(uint256,address,address,uint256,uint256,string,uint256,uint256)": TypedContractEvent<
      FundsClaimedEvent.InputTuple,
      FundsClaimedEvent.OutputTuple,
      FundsClaimedEvent.OutputObject
    >;
    FundsClaimed: TypedContractEvent<
      FundsClaimedEvent.InputTuple,
      FundsClaimedEvent.OutputTuple,
      FundsClaimedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PoolStatusChanged(uint256,bool)": TypedContractEvent<
      PoolStatusChangedEvent.InputTuple,
      PoolStatusChangedEvent.OutputTuple,
      PoolStatusChangedEvent.OutputObject
    >;
    PoolStatusChanged: TypedContractEvent<
      PoolStatusChangedEvent.InputTuple,
      PoolStatusChangedEvent.OutputTuple,
      PoolStatusChangedEvent.OutputObject
    >;

    "ReliefPoolCreated(uint256,uint8,uint8,string,uint256)": TypedContractEvent<
      ReliefPoolCreatedEvent.InputTuple,
      ReliefPoolCreatedEvent.OutputTuple,
      ReliefPoolCreatedEvent.OutputObject
    >;
    ReliefPoolCreated: TypedContractEvent<
      ReliefPoolCreatedEvent.InputTuple,
      ReliefPoolCreatedEvent.OutputTuple,
      ReliefPoolCreatedEvent.OutputObject
    >;
  };
}
